// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4dF3ubD2tE7BPdCISKCZcLk-LfZtQGJw',
    appId: '1:509562141981:web:e884d0d1028880833ab5f4',
    messagingSenderId: '509562141981',
    projectId: 'food-hub-app-2',
    authDomain: 'food-hub-app-2.firebaseapp.com',
    storageBucket: 'food-hub-app-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDkBmbP7zz51hUY_ZoItfdgk7j_ywhErk',
    appId: '1:509562141981:android:f1ef05b9b36276483ab5f4',
    messagingSenderId: '509562141981',
    projectId: 'food-hub-app-2',
    storageBucket: 'food-hub-app-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5acnhfXZD78i-Ur16NcnCvazDUde1QPQ',
    appId: '1:509562141981:ios:653131c95ab9eb3f3ab5f4',
    messagingSenderId: '509562141981',
    projectId: 'food-hub-app-2',
    storageBucket: 'food-hub-app-2.appspot.com',
    iosBundleId: 'com.example.foodHub2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4dF3ubD2tE7BPdCISKCZcLk-LfZtQGJw',
    appId: '1:509562141981:web:69e057a1bd2206ad3ab5f4',
    messagingSenderId: '509562141981',
    projectId: 'food-hub-app-2',
    authDomain: 'food-hub-app-2.firebaseapp.com',
    storageBucket: 'food-hub-app-2.appspot.com',
  );
}
